
package ws.soap.client;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReverseTextWSService", targetNamespace = "http://server.soap.ws/", wsdlLocation = "http://localhost:9999/ReverseTextWS?wsdl")
public class ReverseTextWSService
    extends Service
{

    private final static URL REVERSETEXTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException REVERSETEXTWSSERVICE_EXCEPTION;
    private final static QName REVERSETEXTWSSERVICE_QNAME = new QName("http://server.soap.ws/", "ReverseTextWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ReverseTextWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REVERSETEXTWSSERVICE_WSDL_LOCATION = url;
        REVERSETEXTWSSERVICE_EXCEPTION = e;
    }

    public ReverseTextWSService() {
        super(__getWsdlLocation(), REVERSETEXTWSSERVICE_QNAME);
    }

    public ReverseTextWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVERSETEXTWSSERVICE_QNAME, features);
    }

    public ReverseTextWSService(URL wsdlLocation) {
        super(wsdlLocation, REVERSETEXTWSSERVICE_QNAME);
    }

    public ReverseTextWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVERSETEXTWSSERVICE_QNAME, features);
    }

    public ReverseTextWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReverseTextWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReverseTextWS
     */
    @WebEndpoint(name = "ReverseTextWSPort")
    public ReverseTextWS getReverseTextWSPort() {
        return super.getPort(new QName("http://server.soap.ws/", "ReverseTextWSPort"), ReverseTextWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReverseTextWS
     */
    @WebEndpoint(name = "ReverseTextWSPort")
    public ReverseTextWS getReverseTextWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.ws/", "ReverseTextWSPort"), ReverseTextWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REVERSETEXTWSSERVICE_EXCEPTION!= null) {
            throw REVERSETEXTWSSERVICE_EXCEPTION;
        }
        return REVERSETEXTWSSERVICE_WSDL_LOCATION;
    }

}
