
package ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterestCalculatorWS", targetNamespace = "http://server.soap.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterestCalculatorWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateInterest", targetNamespace = "http://server.soap.ws/", className = "ws.soap.client.CalculateInterest")
    @ResponseWrapper(localName = "calculateInterestResponse", targetNamespace = "http://server.soap.ws/", className = "ws.soap.client.CalculateInterestResponse")
    @Action(input = "http://server.soap.ws/InterestCalculatorWS/calculateInterestRequest", output = "http://server.soap.ws/InterestCalculatorWS/calculateInterestResponse")
    public double calculateInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
